### ISSUE TITLE
Need support for courses required by major, transcript, and prerequisites

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#137]
model level support...

**Comment by liannadevries09** [comment]
@bjmckenz  - not sure what to test here. Can you send me more details?

**Comment by bjmckenz** [comment]
Testing:
* Add required courses to major. Verify you can see them.
* Add course prerequisites to course. Verify you can see them.
* Verify that when a student registers for a course, the course prereqs are shown.
* Verify (when adding course prereq) that you can't make a loop (A->b->C->A) of prereqs.

**Comment by liannadevries09** [comment]
Failed Testing on bullet point 2. 

In courses, then adding a prerequisite to a course, the Save Changes button would not commit. See screenshot. 

![image](https://user-images.githubusercontent.com/71474266/113230167-79a35980-9266-11eb-8191-7a2a2b51f325.png)
![image](https://user-images.githubusercontent.com/71474266/113230205-845dee80-9266-11eb-9bde-1cba79b9b56c.png)

**Comment by bjmckenz** [comment]
perfect..investigating.

**Comment by bjmckenz** [comment]
doesn't appear course-edits are saving at all -- changed jsut the descr and it failed. Investigating.

**Comment by bjmckenz** [comment]
Fixed. The button was broken (since Sunday). BTW, you'll see messages on save/error now
