### ISSUE TITLE
Consider move to true user profile object

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#176]
@oceancypress we left this that you were going to do this, right?

**Comment by bjmckenz** [comment]
Our current model is "first past the finish line":
if there's an Admin, user is admin.
(then) if there's a Professort, then user is Prof
(then) if there's a Student, then user is Student.

Problem is that we don't want to delete the Prof or Student objects because there is history associated with them. So if a user changes from Prof to Student, and we don't delete the Prof object, the user will show up as a prof.

Could handle by adding a "is_active" on the Prof/Stud/Admin object, and ensure that only one is active at a time.

But this militates for a UserProfile with an actual role column. Probably.

**Comment by bjmckenz** [comment]
Testing:
* Ideally no visible changes (there is a "bio" field now in User though).
* editing and creating users is most complicated, esp changing roles.
* touched almost every area of system since it redid all access controls. (sorry)
*

**Comment by liannadevries09** [comment]
Created new roles and touched most of the system. Logged in as student, professor, sysadmin and administrator. I think this can pass.
