### ISSUE TITLE
using abbreviation as a PK in Major is bad from a perf perspective in SQLite, and probably from a customer perspective (cannot change the abbreviation.

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#186]
Consider moving to a proper id/int.

**Comment by bjmckenz** [comment]
Internal. Should be no visible changes.
Testing:
* Majors, create one, edit one
* drill through courses, sections, students, professors, etc.
*

**Comment by liannadevries09** [comment]
looks good
