### ISSUE TITLE
We don't handle graduate students. That's because I assumed that class level was based on credits earned (30,60,90 for So/Jr/Sen).

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#187]
Do we want a student type (undergrad, grad)?

This also enables (makes easier) "grad level classes -- you must be an graduate student to enroll".

@jeffreicher over to you!

**Comment by jeffreicher** [comment]
noted on backlog

**Comment by bjmckenz** [comment]
Testing: 
* log in as admin.
* On Users and Students, filter by grad/undergrad. Verify column is shown in table
* Click into student from there and see level (F-S for undergrad, "graduate" for grad)
* edit a student and switch them -- see results on profile and table
* log in as grad, see header saying "graduate". Same for undergrad.
* Verify student cannot edit this themselves.

**Comment by bjmckenz** [comment]
Known issue (until it's merged) - #454 -- graduate filter on Sections not working.

**Comment by bjmckenz** [comment]
Testing (of final aspects)
* find an undergrad. Try to register for a grad course (id > 500). Fail.
* convert student to grad. Try again. Success!
*
