### ISSUE TITLE
Would like a "next item" / "prev item" on the detail page when viewing one from a long list....

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#196]

**Comment by jeffreicher** [comment]
noted on backlog

**Comment by bjmckenz** [comment]
Testing:
* on Users, Students, Professors, Courses, Semesters, Sections...
* from list, click a row. See a next and/or prev button that takes you to the next based on the order of the table
* (resort the table, verify that the next/prev go to the correct one)
* (verify that there is no Next at end and not Prev at beginning)

*limitation*
* Users/Professors/Students have a weird interaction. Clicking on a Student row in Users may have next/prev based on the last time you clicked on Students -- the order is "its type of table", not Users table. 
* Admins in Users table should "work" correctly.
*
