### ISSUE TITLE
Change password broken?

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#200]
Per @oceancypress

**Comment by bjmckenz** [comment]
Cannot reproduce. 
* Logged in as hades, 
* changed ares password to Suggested Strong. Saved. 
* Logged out as hades, 
* logged in as ares with new pass
* logged out
* logged back in as hades with original pass
* tried to log in as ares with original pass (ares1)

More details, please?

**Comment by oceancypress** [comment]
when I change a password and submit, it goes back to the details page for the user but then when I try signing in with the new password I set it says its wrong. I attempted change the password to "apassword" and it acted like it worked. I'm guessing it did not but just didn't notify me. So maybe we need a message that says it was unsuccessful if it doesnt meet the requirements and it stays on the change password page

**Comment by liannadevries09** [comment]
@bjmckenz - when I changed the password, they log in box came up in the Profile tab  of the schooladmin screen. See screenshot. I dont think that's expected?
![image](https://user-images.githubusercontent.com/71474266/114637950-85484480-9c98-11eb-84f8-0885c455ccf5.png)

**Comment by liannadevries09** [comment]
Actually.. After filling it out, I think that is the way it should work. It's just confirming the password change. I continued with the rest of the test steps and I am passing this one.

**Comment by bjmckenz** [comment]
I filed an issue #357 because I think it's janky.
