### ISSUE TITLE
Last name was optional. Should not be

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#207]
when creating a user, specfically stud

**Comment by bjmckenz** [comment]
Testing:
* try to save or create without one. Go ahead. I'll wait for you.
*

**Comment by liannadevries09** [comment]
I was able to create a student without a last name. I was logged in as an Admin -- just want to make sure that's the create area I should be in. 
![image](https://user-images.githubusercontent.com/71474266/113650744-bc967000-965e-11eb-9cc0-990354112ef9.png)
