### ISSUE TITLE
subordinate tables (e.g. student sections) should have filtering enabled on them

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#215]

**Comment by liannadevries09** [comment]
@bjmckenz  -sorry which screens is this supposed to apply to.

**Comment by liannadevries09** [comment]
Filtering is enabled. Not specifically test each filter but just the presence of them.
Note:  Any screen that has a table on it except for the top pages. Eg within section detail, but not the master sections list.
