### ISSUE TITLE
Semester filters: should have a "SP-2015" place, not just two fields.

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#216]
possibly "enter a date, show active semesters for it"

**Comment by jeffreicher** [comment]
noted in backlog

**Comment by bjmckenz** [comment]
Testing:
* Hit Semesters. See single filter field.
* Type "FA", see all Falls.
* type "2019" see all 2019 semesters
* type "FA-2019"....
*

**Comment by bjmckenz** [comment]
Testing:
* note that this is in addition to the filters -- so if you filter Semesters to FALL and hit Upcoming, you'll only see upcming FALL semesters.

Added:
* Semesters
* * active
* * upcoming
*
