### ISSUE TITLE
Add registration close date.

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#217]
Must be greater than reg start date, must be less than date ended.

**Comment by bjmckenz** [comment]
Testing:
* required on Semester
* validation rules: has to be >= reg open and <= date semester ends
* entered, displayed, sorted anywhere reg open was displayed
* /student should not let you register in a semester that is not "open"

**Comment by liannadevries09** [comment]
Im not seeing a registration close date..
![image](https://user-images.githubusercontent.com/71474266/113650482-44c84580-965e-11eb-983e-8440fcba6eaa.png)

**Comment by oceancypress** [comment]
Seems this isn't quite fixed up @bjmckenz 
![semester_create](https://user-images.githubusercontent.com/48607147/113792408-bbb31c00-96fa-11eb-8e12-e80c47533874.png)

**Comment by oceancypress** [comment]
this seems to be fixed

**Comment by bjmckenz** [comment]
just fixed it. it was an attempt to create a duplicate semester.

**Comment by liannadevries09** [comment]
Tested and working
