### ISSUE TITLE
Adding ability for student to view their grades 

### ISSUE THREAD

**Issue by liannadevries09** [csufmse/student_information_system#220]
TID-42, SID-32

**Comment by bjmckenz** [comment]
hey @liannadevries09, can I finish this one for you?

**Comment by bjmckenz** [comment]
Testing:
* log in as student
* hit My History.

**Comment by liannadevries09** [comment]
@bjmckenz  - sorry missed this message. Yes.. I have tried and learned.. but couldnt get it going.
