### ISSUE TITLE
Only show correct page for user even if the guess a valid id

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#225]
yeah, after thinking on it, I'm not that worried. this may be impacted later when a user can be both a Student and a Professor...but not yet.

**Comment by liannadevries09** [comment]
@bjmckenz  - can this be closed out?

**Comment by bjmckenz** [comment]
yes please @liannadevries09

**Comment by oceancypress** [comment]
closing, see previous comments
