### ISSUE TITLE
on Semester detail, include full name of session

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#230]

**Comment by liannadevries09** [comment]
@bjmckenz  - How can this one be tested?

**Comment by bjmckenz** [comment]
Testing:
* Semesters->Semester
* verify data at top says "SP - Spring" or something like that.not just "SP"
*thanks @liannadevries09

**Comment by liannadevries09** [comment]
looks good:
![image](https://user-images.githubusercontent.com/71474266/113651008-3595c780-965f-11eb-9e1c-055c5c33b958.png)
