### ISSUE TITLE
As a student, I want to be able to view required books for my class

### ISSUE THREAD

**Issue by jeffreicher** [csufmse/student_information_system#233]

**Comment by bjmckenz** [comment]
Testing:
* using /sa, find a course that has ref items for prof, and then section they're teaching.
* log in as student, hit "references"
* ask me if you need data

**Comment by liannadevries09** [comment]
I see required text items.. not necessarily books. But I think this is doing what's expected.
![image](https://user-images.githubusercontent.com/71474266/114492845-5faf3280-9be7-11eb-87f3-5a868fb5134c.png)

**Comment by bjmckenz** [comment]
they;re books if that's what prof entered. You can go enter them, including with link, and see them. (you may need to refresh items for section)
