### ISSUE TITLE
As an administrator, I want to be able to view total student demographics at my school

### ISSUE THREAD

**Issue by jeffreicher** [csufmse/student_information_system#235]
Types of demographics that I'd like to collect
Sex
Race
Ethnicity
Location
Marital Status
Household Income
Employment

As an administrator, I'd like to use these pieces of data to keep our school diverse and they only need to be displayed for me

**Comment by bjmckenz** [comment]
Testing
* Verify that the statistics page lists each demo and the fraction of values
* Verify that statistics can be shown for professors too
* Verify that stat data set can be downloaded as csv

**Comment by bjmckenz** [comment]
@jeffreicher can you give me a sample csv format? Given that there are several dimensions, it's not clear what makes sense. Or ideally you're happy with what's there.

**Comment by jeffreicher** [comment]
@bjmckenz nice job, I think that's fine for now since we have more pressing issues such as adding the graduate students

**Comment by liannadevries09** [comment]
Testing is working but CSV is not included as noted above

**Comment by jeffreicher** [comment]
We'll add the format later on, business accepted as is
