### ISSUE TITLE
As a student, I want to be able to view which of the classes that I've taken would count towards a different major

### ISSUE THREAD

**Issue by jeffreicher** [csufmse/student_information_system#237]

**Comment by bjmckenz** [comment]
Testing:
* sign in as a student. Hit Profile. Below "major courses", see "Explore..."
* Click it. Explore.

**Comment by oceancypress** [comment]
when I hit filter on the sent messages table it gives me a NoReverseMatch error @bjmckenz

**Comment by oceancypress** [comment]
not sure if this matters to you but the filter makes it regress to the major that they are rather than filtering on the new major chosen from the drop down @bjmckenz

**Comment by bjmckenz** [comment]
Yes, that's a known issue -- filters are separate forms and they blow away any other state. This is captured in #271.
