### ISSUE TITLE
As a student, I want to be able to view my current GPA

### ISSUE THREAD

**Issue by jeffreicher** [csufmse/student_information_system#238]

**Comment by bjmckenz** [comment]
This is also fixed by the big profile PR 
Testing:
* log inas a student. 
* Hit Profile.
* See GPA.
*

**Comment by liannadevries09** [comment]
@bjmckenz  - I am not seeing GPA in the My Profile area as a student. Is it because my user doesnt have any completed classes? Should it still display as "GPA: --"?
![image](https://user-images.githubusercontent.com/71474266/114492584-da2b8280-9be6-11eb-8453-61ab91ed0910.png)

**Comment by bjmckenz** [comment]
Good find. I'll do something with it.

**Comment by bjmckenz** [comment]
It's in My History. Profile is kinda....word stuff.  Do you think it should be there too? LMK.
@liannadevries09 

OK, I had fun. I moved the semesters and remaining courses to History (I think they make more sense there).

Then in both History and Test MAjor, I added a summary line: count of classes and credits remaining to graduate. 
(this may not be checked in until later Tuesday).
