### ISSUE TITLE
As a student, I want to be able to view my grades for each class

### ISSUE THREAD

**Issue by jeffreicher** [csufmse/student_information_system#248]
Test by checking student current schedule tag, observe that classes with grades have the grade in the grade column

**Comment by liannadevries09** [comment]
@jeffreicher  - I tried testing this one but do not see the grades column appearing. This is how I tested:
- added a student user
- added a class with a grade associated to it in site admin
- logged in as the student and viewed the Current Schedule page.
- I see the courses appear but do not see a grade column
![image](https://user-images.githubusercontent.com/71474266/113648875-5bb96880-965b-11eb-8229-9369efddea57.png)
![image](https://user-images.githubusercontent.com/71474266/113648933-7d1a5480-965b-11eb-8b0e-2ec23e2b7194.png)
