### ISSUE TITLE
As a administrator, I want to be able to create semester dates

### ISSUE THREAD

**Issue by jeffreicher** [csufmse/student_information_system#252]

**Comment by liannadevries09** [comment]
Got an error when creating new dates on a semester as an admin: [django.db.utils.IntegrityError: UNIQUE constraint failed: sis_semester.semester, sis_semester.year]

![image](https://user-images.githubusercontent.com/71474266/113461580-1db60d80-93eb-11eb-8c89-9c41c1be2edf.png)

**Comment by bjmckenz** [comment]
d'oh. Fixed.
Testing:
* Semesters -> New
* fill fields
* Save
* observe happiness

**Comment by liannadevries09** [comment]
Got an error again:
![image](https://user-images.githubusercontent.com/71474266/113651204-93c2aa80-965f-11eb-9a7f-b2764f7e6c2e.png)
![image](https://user-images.githubusercontent.com/71474266/113651231-9fae6c80-965f-11eb-8e96-bfad248e4884.png)

**Comment by liannadevries09** [comment]
tested and working
