### ISSUE TITLE
As a administrator, I want to be able to edit existing semester dates

### ISSUE THREAD

**Issue by jeffreicher** [csufmse/student_information_system#253]

**Comment by liannadevries09** [comment]
@jeffreicher  - I received an error when editing the semester dates. [NameError: name 'the_update_sem' is not defined]

![image](https://user-images.githubusercontent.com/71474266/113460730-b2b70780-93e7-11eb-9bb2-7f039b5f9a8f.png)

**Comment by liannadevries09** [comment]
@bjmckenz  - retested and this is looking good now.
