### ISSUE TITLE
admin view notifs, handle "Approve drop" (SID-04)

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#262]

**Comment by bjmckenz** [comment]
Partially complete. The administrator is receiving a drop request from the student.

**Comment by bjmckenz** [comment]
Testing: 
* log as a student. Hit Request Drop.
* verify a message comes up in admin My Messages
* and that you can click "Approve"
*

**Comment by liannadevries09** [comment]
approved and working.
