### ISSUE TITLE
Store demographic data in database for students (SID-40)

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#264]

**Comment by bjmckenz** [comment]
@jeffreicher I could use some direction on demographic data. Here are the fields I was planning:

age range: U18, 18-21, 22-25, 26-30, 31-40, 41-55, 55-64, 65+, Decline to State (DTS)

race: white, asian, Native Hawaiian or pac islander, hispanic, black, American Indian or Alaska Native, DTS (see https://www.census.gov/topics/population/race/about.html)

gender: m, f, trans, other, DTS

ethnicity: ?

work status: full time student, part time, full time, unemployed/seeking, retired, DTS

household income - <40K, 40-80k, 80-150k, 150k+, DTS

highest level of education in family: below HS, HS, some college, BS, ms, phd, DTS

family home ownership yes, no, DTS

sexual orientation - cis, L, G, B, T, other, DTS

marital status - single, divorced, widowed, married, DTS

family household size (total) 1, 2-4, 5+, DTS

disability status - none, physical, mental, emotional, DTS 

veteran status: veteran, retired military, not veteran, DTS


**Can you please select a few of these, or suggest a few?**
Thanks!

**Comment by jeffreicher** [comment]
I think we can get rid of ethnicity, sexual orientation, family home ownership, and family household size. Other than that it looks good to start work!

**Comment by bjmckenz** [comment]
Ty. There was a missing one I thought of last night. Trying to remember ...

**Comment by bjmckenz** [comment]
@jeffreicher got it: citizenship. Us, pr, visa, none, dts.

**Comment by liannadevries09** [comment]
Can add all profile items above.
