### ISSUE TITLE
database support for list of textbooks for a class (SID-41)

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#269]

**Comment by bjmckenz** [comment]
DB side implemented, and admin side of creating textbooks, viewing, and linking to a section.

Here's how it works:
* A professor has a list of reference items. He can have as many as he wants for each course in his major, as long as the type and title are different.
* When a section is created or edited, the professor's items are copied from his list into that section. 
* At any time (say the prof adds one) you can hit "refresh items" on the section, or edit it.
*  The list of items for the section are NOT updated any time the prof updates his list; they are only copied over refreshed.
* HOWEVER, he can update the title/descr/etc and that shows up instantly.
* Basically, the number of items in the list doesn't change til you hit refresh.
* Currently can add new items and view them. Did not implement Edit or Delete.
* The items are kinda sorted, but that may be worth usability feedback...

Testing:
* find a prof.
* create an item or two for him for a course he teaches
* Create a section of that course, verify the list is copied over.
* Add a new item to his list, verify it does not update the old section
* create a new section, verify you get the new list.
* (if you could edit items) verify that item edits show up instantly for all sections with it.

@oceancypress The items are available at Section.sectionreferenceitem_set for student display.

**Comment by oceancypress** [comment]
This does not seem testable yet. I do not see where to create reference items in either professor views or admin views. @bjmckenz

**Comment by bjmckenz** [comment]
* find a prof.
* create an item or two for him for a course he teaches

Detail:
* Users, filter for prof. 
* Select one, say 'bgrimm'
* in detail page, scroll to botttom
* click Add Reference Item
* It will show you courses in his dept. Fill out info.
* Now create a section of that class he is teaching, 
* * verify that ref items are shown in the Section
* Alternatively, create the section **before** adding ref items.
* Go to section, and click "refresh reference items"
* see refreshed list.
