### ISSUE TITLE
"semester" field in Semester should be named "session"

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#274]
Semester.semester is a bit confusing and...

**Comment by bjmckenz** [comment]
Testing:
* should be no visible changes; but breaking areas would be:
* Semester create, edit, display
* Section create, edit, display

**Comment by liannadevries09** [comment]
@bjmckenz  - there is no "Add Semester" option that I can see. There are two areas to add a new "Section" (one under semester page and one under section page). I dont know if this broke in this ticket .. let me know if you want me to open a new ticket.

**Comment by bjmckenz** [comment]
there's one at the top of Semesters list

**Comment by liannadevries09** [comment]
Found it! I just needed to back out a bunch because it have clicked into so many linked pages. I received an error. I noted the same error on the Semester Dates ticket.
![image](https://user-images.githubusercontent.com/71474266/113651825-b903e880-9660-11eb-9d48-3381f550b59f.png)

**Comment by oceancypress** [comment]
Still getting this error as seen on #217

**Comment by bjmckenz** [comment]
See #298 - generic issue that we're not catching constraint-fails on object create. Fixed **this** one.

**Comment by oceancypress** [comment]
looks good
