### ISSUE TITLE
collect filtered table html in a template tag

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#275]

**Comment by oceancypress** [comment]
waiting on response from @bjmckenz about whether he wants to take a crack at making render_table work in the tag

**Comment by bjmckenz** [comment]
Pages a working version to branch. It would be nice to use this. It will cut down a lot of html nose.

**Comment by bjmckenz** [comment]
Testing:
* ?Hit everything?
* Seriously, every page that has a table -- sort, filter, and clear filter. And click on row when offered (just guess!)
* I did it by walking down all the urls in the urls.py, and making sure I hit every table on each page.

There should be no functional changes. Except that I changed the page header to show name and userid, not role.

Thanks much!

**Comment by liannadevries09** [comment]
I def didnt touch absolutely everything.. but I tested about 25+ other tickets so I hit every screen that has a table. Going to pass this

**Comment by bjmckenz** [comment]
![](https://media0.giphy.com/media/tsgNNs93oIbwk/giphy.gif)
