### ISSUE TITLE
refactored test data, added creation runner 

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#277]
now you can do:
* from main dir
* python sis/test_data
It will prompt you kinda.

# creates data 
# deletes data
# give it from, to, from&to, only numbers

**Comment by bjmckenz** [comment]
testing:
* rm db.sqlite3
* python manage.py migrate
* python manage.py createsuperuser
* python sis/test_data --create
* verify clean db

**Comment by liannadevries09** [comment]
@bjmckenz  - I received an error testing this... Let me know if it's a "me" problem 
![image](https://user-images.githubusercontent.com/71474266/113651553-32e7a200-9660-11eb-92b2-812c62e08385.png)

**Comment by bjmckenz** [comment]
sorry @liannadevries09  I missed this. It was not a you thing, I think. I fixed a bunch of stuff in the current PR. Can you retest against that?

Note that you need to delete the data first. Either the full db (see the Readme on how to recreate) or use the runner:
python sis/test_data/ --delete

Then do:
python sis/test_data/ --create


Thanks!

**Comment by liannadevries09** [comment]
@bjmckenz  - same error on sis_semester.year and session with a failed unique constraint
![image](https://user-images.githubusercontent.com/71474266/114636861-06520c80-9c96-11eb-83f6-ae89be252e06.png)

**Comment by bjmckenz** [comment]
@liannadevries09 I looked at this. I see how it can happen -- if you didn't delete the test data first. Are you doing the steps in the Readme? Should do "python sis/test-data --delete" before creating it. If you did that, please let me know asap because it would be a big and hairy issue.

Thx.

**Comment by liannadevries09** [comment]
@bjmckenz - when I do the delete I get this error.
![image](https://user-images.githubusercontent.com/71474266/116009503-1f3cb500-a5e8-11eb-92dd-8316647f6e2d.png)
