### ISSUE TITLE
add link to user profile in home page

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#283]
Testing:
* log in.
* verify that clicking the button goes to "your" profile page. (/users/user/id=<hades>)

(particularly useful in testing messages/notifications)

**Comment by bjmckenz** [comment]
Testing:
* from /student and /schooladmin (NOT /professor), hit the Profile button on the left tab bar
* You can edit from there too.

**Comment by liannadevries09** [comment]
Reviewed and working
