### ISSUE TITLE
In Sections edit, capacity shows up twice

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#37]

**Comment by bjmckenz** [comment]
LGTM

**Comment by oceancypress** [comment]
![sections_edit](https://user-images.githubusercontent.com/48607147/112918524-e9c0ac80-90b9-11eb-84b6-ea6a62941094.png)


Seems to be fixed yeah? @bjmckenz

**Comment by oceancypress** [comment]
closing since it seems to be fixed.
