### ISSUE TITLE
No model/concept yet of grades being open or locked (can't set grades after date...)

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#39]
In the current model, grades could be entered for semesters N years ago. I think it'll be fairly easy to build this limit in. Rough estimate: 4 hours, including model and view changes.

I'd like to do this. Can you prioritize it (at what you think it should be)?

**Comment by bjmckenz** [comment]
#112 provides database support for this but application changes are not in place. (The db changes also supported filtering of sections displayed)

Check out Section.STATUSES. should be checked before accepting grades.

**Comment by bjmckenz** [comment]
I think this is complete -- and will be handled by @oceancypress when assigning grades to a section. The section has to be open to do this.

Testing: 
* as professor, view an old section. Try to change grades.
* Denied!

**Comment by liannadevries09** [comment]
This is not working as expected. I am logged in as a professor, looking at an old class. There are two students with grades. There is a Select column with grade options in the dropdown. When I add a grade in the select column, it updates the Grade column to a new value (not the value I picked in the Select dropdown). They are updating eachother in a way that doesnt make sense.. 
![image](https://user-images.githubusercontent.com/71474266/114639012-de18dc80-9c9a-11eb-89da-c0ed5cd2c546.png)

**Comment by bjmckenz** [comment]
Ok, we'll make sure that session is open before allowing grades.

**Comment by bjmckenz** [comment]
Testing: 
* log in as camerica
* select old (WI-2105) and click a section
* See you can't assign grades
* select open sem (SP-2021)
* select a section
* see you can assign grades.
*
