### ISSUE TITLE
refactor user -- remove is_xxx, maybe hack for role

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#69]
Also coalesce the strings and choices for Student, Admin, Prof.

**Comment by bjmckenz** [comment]
The removal of is_ functions was done in #112. But the refactoring for role names has not been done.

**Comment by liannadevries09** [comment]
@bjmckenz - what kinda testing should I do here? Add a user with a role?

**Comment by oceancypress** [comment]
this got merged already
