### ISSUE TITLE
creating methods like name() (Course, Professor, Section...) means that you can't use them in filtering (querysets)

### ISSUE THREAD

**Issue by bjmckenz** [csufmse/student_information_system#86]
I can say `User.objects.filter(last_name='bprofln')` but I can't say `User.objects.filter(name='fn ln')`.

I'm exploring managers and the like to remove this restriction.

**Comment by bjmckenz** [comment]
turns out you can! When you pass data to a list form (semesterS, studentS), wrap the qs in "list(qs)". Take a look at the admin forms. This tells Django to fetch the data and do the sorting in memory. Without it you're sorting by db columns which is not good enough ("gpa" is not a db column). @oceancypress @jeffreicher @liannadevries09

**Comment by liannadevries09** [comment]
@bjmckenz  - should this just be closed out? Looks like it was just for tracking analysis?

**Comment by bjmckenz** [comment]
yes please @liannadevries09

**Comment by oceancypress** [comment]
closing see previous comments
